- name: Install INDI from source
  hosts: localhost
  vars:
    build_dir: /tmp/indi-build
    source_dir: /tmp/indi-git
  tasks:
  - name: Install INDI specific packages
    ansible.builtin.apt:
      pkg:
      - build-essential
      - cdbs
      - cmake
      - dkms
      - fxload
      - git
      - libavcodec-dev
      - libboost-regex-dev
      - libcfitsio-dev
      - libcurl4-gnutls-dev
      - libdc1394-dev
      - libev-dev
      - libfftw3-dev
      - libftdi-dev
      - libgphoto2-dev
      - libgps-dev
      - libgsl-dev
      - libjpeg-dev
      - libkrb5-dev
      - libnova-dev
      - libraw-dev
      - librtlsdr-dev
      - libtheora-dev
      - libtiff-dev
      - libusb-1.0-0-dev
      - libusb-dev
      - zlib1g-dev
  - name: Checkout INDI from github
    ansible.builtin.git:
      repo: https://github.com/indilib/indi.git
      dest: "{{source_dir}}"
      depth: 1
  - name: Create INDI build dir
    ansible.builtin.command:
      cmd: "mkdir {{build_dir}}"
      creates: "{{build_dir}}"
  - name: Run cmake for INDI
    ansible.builtin.command:
      cmd: "cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -B {{build_dir}} -S {{source_dir}}"
      chdir: "{{build_dir}}"
      creates: "{{build_dir}}/Makefile"
  - name: Compile INDI
    ansible.builtin.command:
      cmd: make -j5
      chdir: "{{build_dir}}"
      creates: "{{build_dir}}/indiserver/indiserver"
  - name: Install INDI
    ansible.builtin.command:
      cmd: make install
      chdir: "{{build_dir}}"
      creates: /usr/local/bin/indiserver
  - name: Update library cache after INDI
    ansible.builtin.command:
      cmd: ldconfig

- name: Install INDI 3rdparty from source
  hosts: localhost
  vars:
    build_lib_dir: /tmp/indi-3rd-build-lib
    build_drv_dir: /tmp/indi-3rd-build-drv
    source_dir: /tmp/indi-3rd-git
  tasks:
  - name: Install INDI 3rdparty specific packages
    ansible.builtin.apt:
      pkg:
      - libavcodec-dev
      - libavdevice-dev
      - libboost-dev
      - libboost-regex-dev
      - libcap2-bin
      - libcfitsio-dev
      - libcurl4-gnutls-dev
      - libczmq-dev
      - libdc1394-dev
      - libfftw3-dev
      - libftdi-dev
      - libftdi1-dev
      - libgphoto2-dev
      - libgps-dev
      - libgsl-dev
      - libindi-dev
      - libjpeg-dev
      - liblimesuite-dev
      - libnova-dev
      - libraw-dev
      - librtlsdr-dev
      - libtiff-dev
      - libusb-1.0-0-dev
      - zlib1g-dev
  - name: Checkout INDI 3rdparty from github
    ansible.builtin.git:
      repo: https://github.com/indilib/indi-3rdparty
      dest: "{{source_dir}}"
      depth: 1
  - name: Create INDI 3rdparty libraries build dir
    ansible.builtin.command:
      cmd: "mkdir {{build_lib_dir}}"
      creates: "{{build_lib_dir}}"
  - name: Run cmake for INDI 3rdparty libraries
    ansible.builtin.command:
      cmd: "cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_LIBS=1 -B {{build_lib_dir}} -S {{source_dir}}"
      chdir: "{{build_lib_dir}}"
      creates: "{{build_lib_dir}}/Makefile"
  - name: Compile INDI 3rdparty libraries
    ansible.builtin.command:
      cmd: make -j5
      chdir: "{{build_lib_dir}}"
      creates: "{{build_lib_dir}}/libqhy/libqhyccd.so"
  - name: Install INDI 3rdparty libraries
    ansible.builtin.command:
      cmd: make install
      chdir: "{{build_lib_dir}}"
      creates: /usr/local/lib/libqhyccd.so
  - name: Update library cache after INDI 3rdparty
    ansible.builtin.command:
      cmd: ldconfig
  - name: Create INDI 3rdparty drivers build dir
    ansible.builtin.command:
      cmd: "mkdir {{build_drv_dir}}"
      creates: "{{build_drv_dir}}"
  - name: Run cmake for INDI 3rdparty drivers
    ansible.builtin.command:
      cmd: "cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -B {{build_drv_dir}} -S {{source_dir}}"
      chdir: "{{build_drv_dir}}"
      creates: "{{build_drv_dir}}/Makefile"
  - name: Compile INDI 3rdparty drivers
    ansible.builtin.command:
      cmd: make -j5
      chdir: "{{build_drv_dir}}"
      creates: "{{build_drv_dir}}/indi-qhy/indi_qhy_ccd"
  - name: Install INDI 3rdparty drivers
    ansible.builtin.command:
      cmd: make install
      chdir: "{{build_drv_dir}}"
      creates: /usr/local/bin/indi_qhy_ccd
