- name: Update Ubuntu packages
  hosts: localhost
  tasks:
  - name: Install latest packages
    ansible.builtin.apt:
      pkg:
      - astrometry-data-tycho2
      - astrometry.net
      - build-essential
      - cmake
      - curl
      - doxygen
      - g++
      - gcc
      - gettext
      - git 
      - gnome-keyring
      - graphviz
      - libcfitsio-dev
      - libdrm-dev
      - libgl1-mesa-dev
      - libusb-1.0-0-dev
      - libxcb-xinerama0
      - subversion
      - wget
      - zlib1g-dev

- name: Install OpenCV from source - v3.16
  hosts: localhost
  vars:
    build_dir: /tmp/opencv-3.4.16/build
  tasks:
  - name: Install OpenCV specific packages
    ansible.builtin.apt:
      pkg:
      - libavcodec-dev
      - libavformat-dev
      - libdc1394-dev
      - libgtk2.0-dev
      - libjpeg-dev
      - libpng-dev
      - libswscale-dev
      - libtbb-dev
      - libtbb2
      - libtiff-dev
      - pkg-config
      - python3-dev
      - python3-numpy
  - name: Unzip
    ansible.builtin.command:
      cmd: tar xzf 3.4.16.tar.gz
      chdir: /tmp/
      creates: /tmp/opencv-3.4.16/
  - name: Create build dir
    ansible.builtin.command:
      cmd: "mkdir {{build_dir}}"
      creates: "{{build_dir}}"
  - name: Run cmake
    ansible.builtin.command:
      cmd: "cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -B {{build_dir}} -S /tmp/opencv-3.4.16/"
      chdir: "{{build_dir}}"
      creates: "{{build_dir}}/Makefile"
  - name: Compile
    ansible.builtin.command:
      cmd: make -j5
      chdir: "{{build_dir}}"
      creates: "{{build_dir}}/bin/opencv_version"
  - name: Install
    ansible.builtin.command:
      cmd: make install
      chdir: "{{build_dir}}"
      creates: /usr/local/bin/opencv_version
  - name: Ensure local libraries are used
    ansible.builtin.lineinfile:
      path: /etc/ld.so.conf.d/libc.conf
      search_string: /usr/local/lib
      line: /usr/local/lib
  - name: Update library cache
    ansible.builtin.command:
      cmd: ldconfig

- name: Install QHYCCD SDK
  hosts: localhost
  tasks:
  - name: Download tarball
    ansible.builtin.get_url:
      url: https://www.qhyccd.com/file/repository/publish/SDK/240109/sdk_linux64_24.01.09.tgz
      dest: /tmp/sdk_linux64_24.01.09.tgz
  - name: Extract
    ansible.builtin.command:
      cmd: tar xf sdk_linux64_24.01.09.tgz
      chdir: /tmp/
      creates: /tmp/sdk_linux64_24.01.09
  - name: Install
    ansible.builtin.command:
      cmd: bash install.sh
      chdir: /tmp/sdk_linux64_24.01.09
      creates: /usr/sbin/fxload

- name: Install INDI from source
  hosts: localhost
  vars:
    build_dir: /tmp/indi-build
    source_dir: /tmp/indi-git
  tasks:
  - name: Install INDI specific packages
    ansible.builtin.apt:
      pkg:
      - build-essential
      - cdbs
      - cmake
      - dkms
      - fxload
      - git
      - libavcodec-dev
      - libboost-regex-dev
      - libcfitsio-dev
      - libcurl4-gnutls-dev
      - libdc1394-dev
      - libev-dev
      - libfftw3-dev
      - libftdi-dev
      - libgphoto2-dev
      - libgps-dev
      - libgsl-dev
      - libjpeg-dev
      - libkrb5-dev
      - libnova-dev
      - libraw-dev
      - librtlsdr-dev
      - libtheora-dev
      - libtiff-dev
      - libusb-1.0-0-dev
      - libusb-dev
      - zlib1g-dev
  - name: Checkout from github
    ansible.builtin.git:
      repo: https://github.com/indilib/indi.git
      dest: "{{source_dir}}"
      depth: 1
  - name: Create build dir
    ansible.builtin.command:
      cmd: "mkdir {{build_dir}}"
      creates: "{{build_dir}}"
  - name: Run cmake
    ansible.builtin.command:
      cmd: "cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -B {{build_dir}} -S {{source_dir}}"
      chdir: "{{build_dir}}"
      creates: "{{build_dir}}/Makefile"
  - name: Compile
    ansible.builtin.command:
      cmd: make -j5
      chdir: "{{build_dir}}"
      creates: "{{build_dir}}/indiserver/indiserver"
  - name: Install
    ansible.builtin.command:
      cmd: make install
      chdir: "{{build_dir}}"
      creates: /usr/local/bin/indiserver
  - name: Update library cache
    ansible.builtin.command:
      cmd: ldconfig

- name: Install INDI 3rdparty from source
  hosts: localhost
  vars:
    build_dir: /tmp/indi-3rd-build
    source_dir: /tmp/indi-3rd-git
  tasks:
  - name: Install INDI 3rdparty specific packages
    ansible.builtin.apt:
      pkg:
      - libavcodec-dev
      - libavdevice-dev
      - libboost-dev
      - libboost-regex-dev
      - libcfitsio-dev
      - libcurl4-gnutls-dev
      - libdc1394-dev
      - libfftw3-dev
      - libftdi-dev
      - libftdi1-dev
      - libgphoto2-dev
      - libgps-dev
      - libgsl-dev
      - libindi-dev
      - libjpeg-dev
      - liblimesuite-dev
      - libnova-dev
      - libraw-dev
      - librtlsdr-dev
      - libtiff-dev
      - libusb-1.0-0-dev
      - zlib1g-dev
  - name: Checkout from github
    ansible.builtin.git:
      repo: https://github.com/indilib/indi-3rdparty
      dest: "{{source_dir}}"
      depth: 1
  - name: Create build dir
    ansible.builtin.command:
      cmd: "mkdir {{build_dir}}"
      creates: "{{build_dir}}"
  - name: Run cmake
    ansible.builtin.command:
      cmd: "cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_LIBS=1 -B {{build_dir}} -S {{source_dir}}"
      chdir: "{{build_dir}}"
      creates: "{{build_dir}}/Makefile"
  - name: Compile
    ansible.builtin.command:
      cmd: make -j5
      chdir: "{{build_dir}}"
      creates: "{{build_dir}}/libqhy/libqhyccd.so"
  - name: Install
    ansible.builtin.command:
      cmd: make install
      chdir: "{{build_dir}}"
      creates: /usr/local/lib/libqhyccd.so
  - name: Update library cache
    ansible.builtin.command:
      cmd: ldconfig

